### ISSUE TITLE
MooX::StrictConstructor incompatible with sensitive fields

### ISSUE THREAD

**Issue by jrubinator** [hartzell/moox-strictconstructor#19]
If `MooX::StrictConstructor` catches an extra field, it dumps a stack trace with `confess`. While this is helpful for debugging, it can create insecurities, eg.

```
$ cat test.pl
use strict;
use warnings;

package Foo;

use Moo;
use MooX::StrictConstructor;

has password => ( is  => 'ro' );

package main;

Foo->new(
    password    => "THIS SHOULD NOT BE IN STACK TRACE!",
    extra_field => 1,
);
$ perl test.pl
Found unknown attribute(s) passed to the constructor: extra_field at (eval 12) line 49.
        Foo::new("Foo", "password", "THIS SHOULD NOT BE IN STACK TRACE!", "extra_field", 1) called at test.pl line 13
```

Would you be amenable to/have any suggestions for a patch to fix this?

**Comment by hartzell** [comment]
I believe that there are standard/common ways of eliding things like passwords from traces/logs/....

I'd be interested to see what such a solution might look like (sketch first, then perhaps a PR).  It'd be great if it were similar to/the same as solutions used by other MooX modules.

**Comment by jrubinator** [comment]
> I believe that there are standard/common ways of eliding things like passwords from traces/logs/....

I know you can elide things using eg. `Devel::StackTrace`, but I'm not sure there are reliable tools out there once the exception has been stringified (as per `Carp::confess`). And once the exception _is_ stringified, you lose some options (like turning off all argument capturing via `Devel::StackTrace`).

> I'd be interested to see what such a solution might look like (sketch first, then perhaps a PR). It'd be great if it were similar to/the same as solutions used by other MooX modules.

Alas, I'm not sure what to do here. The way I see it, you can:
* die with a string without a trace (this module used to do so, but errors were hard to diagnose)
* die with a string and a trace (which leads to the current dilemma)
* die with an object (not necessarily compatible across Moo)

I'm not that familiar with the ecosystem - I have to defer to your thoughts there.

**Comment by hartzell** [comment]
How about if I told you that this wasn't this Module's problem, and that rather than trying to fix this one particular symptom of "your" problem (this module confessing) you should instead fix the way that your data's stored so that none of the various ways that Perl can bail out will end up biting you?

One solution could be to use [Store::Opaque](https://metacpan.org/pod/Store::Opaque) for your password (and other sensitive) fields.  It hasn't been touched in a while, but on the other hand it's such a simple module that it might not have any other needs.

If that doesn't work for you, you could ask in one of the Perl (Moose) groups and see if there are any modern equivalents, and/or how other people are handling the problem.   I have a feeling that this is a solved/worked-around problem.

There might even be an opportunity to to wrap up a new MooX::Role::Opaque that makes it simple to add class attributes that use the trick from (or even just use...) Store::Opaque to hide their values from stack traces.

**Comment by hartzell** [comment]
PS: Another useful link with [background for Store::Opaque](https://medium.com/booking-com-development/protect-against-accidental-logging-of-sensitive-information-816f55976522).

**Comment by jrubinator** [comment]
> How about if I told you that this wasn't this Module's problem, and that rather than trying to fix this one particular symptom of "your" problem (this module confessing) you should instead fix the way that your data's stored so that none of the various ways that Perl can bail out will end up biting you?

I do think that `Store::Opaque` would work for the one particular instance that prompted me to file this. And saying to use `Store::Opaque` would certainly be a good policy. But that requires active preventative behavior from developers, whereas removing traces passively protects data. Your suggestion for `MooX::Role::Opaque` is intriguing as well, and a little less likely to be forgotten. I'll probably look into that.

One might also argue that providing a full stack trace is not this module's concern either - if someone wants stack traces on their exceptions they can always use [Carp::Always](https://metacpan.org/pod/Carp%3A%3AAlways). This module only needs to provide the error.

So I think I've talked myself into thinking that not using `confess` is correct :) That said, I totally get that behavior is not backwards compatible, and if you want to close this as "Won't Do", I understand.

Thank you for taking the time to talk this through!

**Comment by hartzell** [comment]
Ok, I think we're on the same page.  I thought that you were suggesting that `MooX::StrictConstructor` somehow mask your/the sensitive info before confess'ing.  You're actually arguing that it should `die` instead of `confess`.

I'd take a PR that made that change, documented it, and added a reference/example for using `Carp::Always` in the docs.

> But that requires active preventative behavior from developers, whereas removing traces passively protects data.

Even given the above, if I were reviewing your application code, I'd still flag it; all you're doing is playing whack-a-mole with bits of code that might accidentally expose your secrets (stack traces, logging, debug print statements left in code, etc.., etc...).  Even if you catch them all now, someone who inherits your app might add something that exposes them or one of your dependencies might change behavior while you're not paying attention.

Hiding them (Store::Opaque or ...) is the only actually safe alternative.  The developers know what's sensitive and they're the best ones to ensure that it's hidden.
